### PR TITLE
Reloading instead of restarting server

### PR DESCRIPTION
**Pull request by SwannCroiset**

### CODE REVIEW

**Comment by geerlingguy** [comment]
It seems like this would be a simpler solution: https://github.com/geerlingguy/ansible-role-nfs/pull/26, closing in favor of that PR.

**Comment by vincent-legoll** [comment]
Oh, I did not see this one before doing my PR, sorry...

**Comment by SwannCroiset** [comment]
@vincent-legoll no worries, your solution is much better. Thanks

**Comment by geerlingguy** [comment]
(FYI I really wish there were a way to give some sort of 'partial commit credit' or something for things like this—both PRs are valuable, but there's no easy way in the git history to say "this PR was great / earlier, but the second PR was the merged one" :/

**Pull request closed without merging**
