### PR TITLE
Make exports more configurable #24

### PR DESCRIPTION
**Pull request by jadjay**
I send another one to add state in README :)

### CODE REVIEW

**Comment by vincent-legoll** [comment]
This looks interesting, but I'd go further with the options, like you did for acls,and allow something like the following:

```
nfs_exports:
  - name: "Public"
    path: "/home/public"
    options:
      "*":
        - rw
        - sync
        - no_root_squash
      "10.0.0.1":
        - ro
      "10.0.0.2": ["rw", "sync"]
    state: "present"
    acls:
      mode: 777
      owner: user
      group: group
```

**Comment by jadjay** [comment]
Yes that's great.

**Comment by jadjay** [comment]
@vincent-legoll 
Ok now propose a commit for this  :)

**Comment by geerlingguy** [comment]
This seems like it would be a major breaking change for any current role users. Also, I typically tend to shy away from breaking out simple config (e.g. oneline for each export) into separate parameters, just because for someone used to the exports syntax, that adds more mental weight of 'how do I break this up into individual config options'.

That said... I'm not totally against this change. But it would require a major version bump, since it would break everyone's playbooks.

**Comment by vincent-legoll** [comment]
Maybe the role could have 2 different ways of configuring the exports file: 
nfs_exports: ['...', '...'] # To keep compatibility with existing uses
nfs_exports_detailed: [...] # As above

You can either add the two, which will require users to be careful not to overwrite one conf with the other, or make them exclusive of each other...

This would complicate the role a bit, but not by much, I think.
If this is agreed upon, I may attempt to do it...

My choice for a first version would be with the exclusive way.

**Comment by jadjay** [comment]
@vincent-legoll Maybe if you propose a commit, it will be better than just comments...

**Comment by vincent-legoll** [comment]
I've no time to work on this right now, but if no one beats me to it, I'll revisit this later.

**Pull request closed without merging**
